export const softwareList = {
  data: [
    {
      application: 'IntelliJ IDEA',
      download_link: 'https://www.jetbrains.com/idea/',
      docs: 'https://www.jetbrains.com/idea/documentation/',
      version: 'Latest',
      platform: 'all',
      category: 'Text Editors & IDE',
    },
    {
      application: 'Eclipse',
      download_link: 'https://www.eclipse.org/',
      docs: 'https://www.eclipse.org/documentation/',
      version: 'Latest',
      platform: 'all',
      category: 'Text Editors & IDE',
    },
    {
      application: 'Git',
      download_link: 'https://git-scm.com/',
      docs: 'https://git-scm.com/doc',
      version: 'Latest',
      platform: 'all',
      category: 'Version Control',
    },
    {
      application: 'GitHub Desktop',
      download_link: 'https://desktop.github.com/',
      docs: 'https://docs.github.com/desktop',
      version: 'Latest',
      platform: 'all',
      category: 'Version Control',
    },
    {
      application: 'Bitbucket',
      download_link: 'https://bitbucket.org/product',
      docs: 'https://support.atlassian.com/bitbucket-cloud/',
      version: 'Latest',
      platform: 'all',
      category: 'Version Control',
    },

    {
      application: 'Node.js',
      download_link: 'https://nodejs.org/',
      docs: 'https://nodejs.org/en/docs/',
      version: 'Latest',
      platform: 'all',
      category: 'Languages & Runtimes',
    },
    {
      application: 'NVM (Node Version Manager)',
      download_link:
        'https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe',
      docs: 'https://github.com/coreybutler/nvm-windows/wiki#manual-installation',
      version: '1.1.11',
      platform: 'windows',
      category: 'Package Managers',
    },
    {
      application: 'MySQL Community Server',
      download_link: 'https://dev.mysql.com/downloads/file/?id=520510',
      docs: 'https://dev.mysql.com/doc/',
      version: '8.1.0',
      platform: 'all',
      category: 'Database Management',
    },
    {
      application: 'MySQL Workbench',
      download_link: 'https://www.mysql.com/products/workbench/',
      docs: 'https://dev.mysql.com/doc/workbench/en/',
      version: '8.0.34',
      platform: 'all',
      category: 'Database Management',
    },
    {
      application: 'MongoDB',
      download_link: 'https://www.mongodb.com/',
      docs: 'https://docs.mongodb.com/',
      version: 'Latest',
      platform: 'all',
      category: 'Database Management',
    },
    {
      application: 'Sublime Text',
      download_link: 'https://www.sublimetext.com/',
      docs: 'https://www.sublimetext.com/docs/',
      version: 'Latest',
      platform: 'all',
      category: 'Text Editors & IDE',
    },
    {
      application: 'Notepad++',
      download_link: 'https://notepad-plus-plus.org/downloads/',
      docs: 'https://notepad-plus-plus.org/',
      version: 'Latest',
      platform: 'all',
      category: 'Text Editors & IDE',
    },
    {
      application: 'Postman',
      download_link: 'https://www.postman.com/downloads/',
      docs: 'https://learning.postman.com/docs/',
      version: 'Latest',
      platform: 'all',
      category: 'API Development',
    },

    {
      application: 'Slack',
      download_link: 'https://slack.com/',
      docs: 'https://slack.com/help/',
      version: 'Latest',
      platform: 'all',
      category: 'Collaboration Tools',
    },
    {
      application: 'Chocolatey',
      download_link: 'https://chocolatey.org/install',
      docs: 'https://docs.chocolatey.org/en-us/',
      version: 'Latest',
      platform: 'windows',
      category: 'Package Managers',
    },
    {
      application: 'Android Studio',
      download_link: 'https://developer.android.com/studio/index.html',
      docs: 'https://developer.android.com/docs',
      version: 'Latest',
      platform: 'windows',
      category: 'Text Editors & IDE',
    },
    {
      application: 'iTerm2',
      download_link: 'https://iterm2.com/',
      docs: 'https://iterm2.com/documentation.html',
      version: 'Latest',
      platform: 'macOS',
      category: 'Shell & Terminal',
    },
    {
      application: 'Homebrew',
      download_link: 'https://brew.sh/',
      docs: 'https://docs.brew.sh/',
      version: 'Latest',
      platform: 'macOS',
      category: 'Package Managers',
    },
    {
      application: 'Oh My Zsh',
      download_link: 'https://ohmyz.sh/',
      docs: 'https://github.com/ohmyzsh/ohmyzsh/wiki',
      version: 'Latest',
      platform: 'macOS',
      category: 'Shell & Terminal',
    },
    {
      application: 'alfred',
      download_link: 'https://www.alfredapp.com/',
      docs: 'https://www.alfredapp.com/help/',
      version: 'Latest',
      platform: 'macOS',
      category: 'Productivity Tools',
    },
    {
      application: 'XAMPP',
      download_link: 'https://www.apachefriends.org/download.html',
      docs: 'https://www.apachefriends.org/index.html',
      version: 'Latest',
      platform: 'all',
      category: 'Server',
    },
    {
      application: 'Warp',
      download_link: 'https://www.warp.dev/',
      docs: 'https://docs.warp.dev/getting-started/readme',
      version: 'Latest',
      platform: 'macOS',
      category: 'Shell & Terminal',
    },
    {
      application: 'Magnet',
      download_link: 'https://apps.apple.com/us/app/magnet/id441258766?mt=12',
      docs: 'N/A',
      version: 'Latest',
      platform: 'macOS',
      category: 'Productivity Tools',
    },
    {
      application: 'Sourcetree',
      download_link: 'https://www.sourcetreeapp.com/',
      docs: 'N/A',
      version: 'Latest',
      platform: 'window',
      category: 'Version Control',
    },
  ],

  types: {
    application: 'string',
    download_link: 'string',
    docs: 'string',
    version: 'string',
    platform: 'string',
    category: 'string',
  },
};
